export const ENTER_IMAGE_URL="ENTER_IMAGE_URL";
export const REGISTRATION_NAME="REGISTRATION_NAME";
export const REGISTRATION_EMAIL="REGISTRATION_EMAIL";
export const REGISTRATION_PASSWORD="REGISTRATION_PASSWORD"; 
// export const LOAD_USERS_PENDING="LOAD_USERS_PENDING";
// export const LOAD_USERS_SUCCESS="LOAD_USERS_PENDING";
// export const LOAD_USERS_FAILED="LOAD_USERS_PENDING";